language: node_js
node_js:
- '8'
- '10'
cache: yarn
script: yarn ci
deploy:
  provider: npm
  email: igor@kamyshev.me
  skip_cleanup: true
  api_key:
    secure: rJmwaR1wtXZQCN0acIJy0vZ19idA7DHa72TOVUGNsYbvX6OhYyXOwU4eftRKXgjESg8IG5jF0jAN2PEHfSyLnl08qkFsv7+pzEnE+LnDcfsw4VAtNE2b2BvAlbUDYzR4l6QR1n/lvRxAitqBa05rLxtfrkXj0jTiZlRbT1TtMzN5MzHg4xFyGbENoTndRd9AiQwFU3Ham3yZT0OZDb5EtKO5CoZrdO4eNVrJTiT/KSi3JIRGkPvj6AbVr0ku93G+93+IcrNQw8qm3R9++SxvKAIh5aOyMXIOAlT/CIAhi/4CXtMa1IJW2EwStrHZymvw0hx2HXixmiHvRT0wMYgQqPJyHYEqO8ikQBPqskn7oFiZItoHvdg/W2Jb3QVOV4sywjXRlbbOQmAXQg9WK5+qvM8nmg5sfKSLqI/1NWrutlgsoyfo6bZ7xf8IWi5Os7MTp8p1B4YoLQOO1b3lbZ6tGL7TaJn3n0d0cPu2hSzmj39Pr9lMyVdA8iHeS9LyfIfNiRKZ546TsJO/UuojibBy696jjOWdradnW+bpHUNQ3a4lM6f4HjtcAgm3YeRwkPWGTcuMAObh15aHJuB3DGiqqplD6QhQZgz1/urW9f4u4I46QnVp24hKXun/ee58Rv7hLLB9rvvTGIEAbTZtMongWa7jdUH7QKD5/M/2iS1Hxcs=
  on:
    tags: true
    repo: igorkamyshev/nest-telegram
